#!/usr/bin/env python3
"""Generate the PostgreSQL extension ImageVolume Containerfile."""

from __future__ import annotations

import json
from pathlib import Path
from string import Template


ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "extensions.json"
OUTPUT = ROOT / "images" / "Containerfile.extensions"


def render_arg_name(extension_id: str, suffix: str) -> str:
    return f"{extension_id.upper().replace('-', '_')}_{suffix}"


def render_copy_lines(extensions: list[dict], kind: str) -> list[str]:
    lines: list[str] = []
    for extension in extensions:
        if not extension["enabled"] or not extension.get("copy", {}).get(kind, False):
            continue

        copy_arg = render_arg_name(extension["id"], "COPY")
        if kind == "license":
            package_arg = render_arg_name(extension["id"], "PACKAGE")
            lines.append(
                f"COPY --from=builder /usr/share/doc/${{{package_arg}}}/copyright /licenses/${{{package_arg}}}/"
            )
        elif kind == "lib":
            lines.append(
                f"COPY --from=builder /usr/lib/postgresql/${{PG_MAJOR}}/lib/${{{copy_arg}}}* /lib/"
            )
        elif kind == "share":
            lines.append(
                f"COPY --from=builder /usr/share/postgresql/${{PG_MAJOR}}/extension/${{{copy_arg}}}* /share/extension/"
            )
        else:
            raise ValueError(f"Unknown copy kind: {kind}")
    return lines


def render() -> str:
    manifest = json.loads(MANIFEST.read_text())
    enabled = [extension for extension in manifest["extensions"] if extension["enabled"]]
    pigsty = next(source for source in manifest["aptSources"] if source["name"] == "pigsty")

    package_args = "\n".join(
        f"ARG {render_arg_name(extension['id'], 'PACKAGE')}={extension['package']}" for extension in enabled
    )
    version_args = "\n".join(
        f"ARG {render_arg_name(extension['id'], 'VERSION')}={extension['version']}" for extension in enabled
    )
    copy_args = "\n".join(
        f"ARG {render_arg_name(extension['id'], 'COPY')}={extension['copyName']}" for extension in enabled
    )
    install_lines = " \\\n  ".join(
        f'"${{{render_arg_name(extension["id"], "PACKAGE")}}}=${{{render_arg_name(extension["id"], "VERSION")}}}"'
        for extension in enabled
    )
    probe_lines = " \\\n  ".join(
        f"/usr/lib/postgresql/${{PG_MAJOR}}/lib/{library}"
        for library in manifest["dependencyProbeLibraries"]
    )

    template = Template(
        """# Generated by scripts/generate-containerfile.py from extensions.json. Do not edit by hand.
ARG BASE=$base_image
FROM $$BASE AS builder

ARG PG_MAJOR=$postgres_major
ARG PKG_PREFIX=postgresql-$${PG_MAJOR}

$package_args

$version_args

USER 0

RUN apt-get update && \\
  ldconfig -p | awk '{print $$NF}' | grep '^/' | sort | uniq > /tmp/base-image-libs.out && \\
  apt-get install -y curl ca-certificates gnupg && \\
  mkdir -p /etc/apt/keyrings && \\
  curl -fsSL $pigsty_key_url | gpg --dearmor -o /etc/apt/keyrings/pigsty.gpg && \\
  echo "$pigsty_apt_line" | tee /etc/apt/sources.list.d/pigsty-io.list > /dev/null && \\
  apt-get update && \\
  apt-get install -y --no-install-recommends \\
  $install_lines \\
  && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /system /licenses

RUN ldd \\
  $probe_lines \\
  | awk '{print $$3}' | grep '^/' | sort | uniq > /tmp/all-deps.out

RUN comm -13 /tmp/base-image-libs.out /tmp/all-deps.out > /tmp/libraries.out

RUN while read -r lib; do \\
  resolved=$$(readlink -f "$$lib"); \\
  dir=$$(dirname "$$lib"); \\
  base=$$(basename "$$lib"); \\
  cp -a "$$resolved" /system/; \\
  for file in "$$dir"/"$${base%.so*}.so"*; do \\
    [ -e "$$file" ] || continue; \\
    if [ -L "$$file" ] && [ "$$(readlink -f "$$file")" = "$$resolved" ]; then \\
      ln -sf "$$(basename "$$resolved")" "/system/$$(basename "$$file")"; \\
    fi; \\
  done; \\
  done < /tmp/libraries.out

FROM scratch

ARG PG_MAJOR=$postgres_major
ARG PKG_PREFIX=postgresql-$${PG_MAJOR}

$package_args

$copy_args

# Licenses
COPY --from=builder /licenses /licenses/
$license_copy_lines

# Libraries
$lib_copy_lines
COPY --from=builder /usr/lib/postgresql/$${PG_MAJOR}/lib/bitcode/ /lib/bitcode/

# Share
$share_copy_lines

# System libs
COPY --from=builder /system /system/

USER 65532:65532
"""
    )

    rendered = template.substitute(
        base_image=manifest["baseImage"],
        postgres_major=manifest["postgresMajor"],
        package_args=package_args,
        version_args=version_args,
        pigsty_key_url=pigsty["keyUrl"],
        pigsty_apt_line=pigsty["aptLine"],
        install_lines=install_lines,
        probe_lines=probe_lines,
        copy_args=copy_args,
        license_copy_lines="\n".join(render_copy_lines(enabled, "license")),
        lib_copy_lines="\n".join(render_copy_lines(enabled, "lib")),
        share_copy_lines="\n".join(render_copy_lines(enabled, "share")),
    )
    return rendered.rstrip() + "\n"


def main() -> None:
    OUTPUT.write_text(render())


if __name__ == "__main__":
    main()
